apiVersion: v1
data:
  tls.crt: Zm9vIC1uCg==
  tls.key: Zm9vIC1uCg==
kind: Secret
metadata:
  annotations:
    replicator.v1.mittwald.de/replicate-from: jx/tls-jx-wolkenreich-swiss-p
  name: "tls-jx-wolkenreich-swiss-p"
type: kubernetes.io/tls
